'use client'

import './globals.css'
import { Roboto } from 'next/font/google';

import { Container } from '@mui/material';
import NavigationBar from '../components/NavigationBar';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className} >
        <NavigationBar />
        <Container>
          {children}
        </Container>

      </body>
    </html>
  )
}
